FROM       python:3.7
MAINTAINER Rodrigo Orellana <rodrigo.usm@gmail.com>

# Update apt-get sources AND install Python-dve
#RUN apt-get update && apt-get install -y build-essential python-dev 
#RUN apt-get install -y python-setuptools
#RUN apt-get install -y python-pip
#RUN apt-get install -y nano
#RUN apt-get install -y telnet

## Flask Extensions
RUN pip3 install flask
#RUN pip3 install flask-wtf
#RUN pip3 install flask-bootstrap
#RUN pip3 install flask-pymongo
#RUN pip3 install flask-mail
RUN pip3 install pymongo
RUN pip3 install pmdarima
RUN pip3 install pandas
RUN pip3 install statsmodels



## Install a few other tools, nano, telnet and so on...
#RUN apt-get install -y nano && apt-get install -y telnet

EXPOSE 8001

ENTRYPOINT ["python" , "/app1/prediction.py"]
